language: minimal
os: linux

# Integration tests need to run first to reset the PR build status to pending
stages:
  - name: 'Trigger Integration Tests'
    if: env(RUN_COMPAT_SUITE) = true
  - name: 'SourceClear and Lint'
  - name: 'Unit Tests'
  - name: 'Prepare for release'
    if: env(PREP) = true and type = api
  - name: 'Release'
    if: env(RELEASE) = true and type = api

jobs:
  include:
    - stage: 'Trigger Integration Tests'
      language: minimal
      os: linux
      env:
        - SDK=swift
        - BUILD_NUMBER=$TRAVIS_BUILD_NUMBER
        - TESTAPP_TAG=master
      cache: false
      install:
        - mkdir $HOME/travisci-tools && pushd $HOME/travisci-tools && git init && git pull https://$CI_USER_TOKEN@github.com/optimizely/travisci-tools.git && popd
      script:
        - "$HOME/travisci-tools/fsc-trigger/trigger_fullstack-sdk-compat.sh"

    - stage: 'SourceClear and Lint'
      language: swift
      os: osx
      osx_image: xcode10.1
      addons:
        srcclr: true
      install: gem install cocoapods
      script:
        - pod spec lint --quick

    - &unittests
      stage: 'Unit Tests'
      language: swift
      os: osx
      osx_image: xcode10.1
      branches:
        only:
          - master
      env: SCHEME=OptimizelySwiftSDK-iOS TEST_SDK=iphonesimulator PLATFORM='iOS Simulator' OS=9.1 NAME='iPad Air'
      name: PLATFORM='iOS Simulator' OS=9.1 NAME='iPad Air'
      before_install:
        - gem install slather --no-document --quiet
      install:
        - pod install --repo-update
      script:
        - pod spec lint --quick
        - travis_wait xcodebuild test -workspace OptimizelySDK.xcworkspace -scheme $SCHEME -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk $TEST_SDK -destination "platform=$PLATFORM,OS=$OS,name=$NAME" ONLY_ACTIVE_ARCH=YES | xcpretty; test ${PIPESTATUS[0]} -eq 0
        - travis_wait xcodebuild test -workspace OptimizelySDK.xcworkspace -scheme OptimizelySwiftSDK-iOS -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk iphonesimulator -destination "platform=iOS Simulator,OS=10.1,name=iPhone 7 Plus" ONLY_ACTIVE_ARCH=YES | xcpretty; test ${PIPESTATUS[0]} -eq 0
        - travis_wait xcodebuild test -workspace OptimizelySDK.xcworkspace -scheme OptimizelySwiftSDK-iOS -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk iphonesimulator -destination "platform=iOS Simulator,OS=10.3.1,name=iPhone 7" ONLY_ACTIVE_ARCH=YES | xcpretty; test ${PIPESTATUS[0]} -eq 0
        - travis_wait xcodebuild test -workspace OptimizelySDK.xcworkspace -scheme OptimizelySwiftSDK-tvOS -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk appletvsimulator -destination "platform=tvOS Simulator,OS=10.2,name=Apple TV 1080p" ONLY_ACTIVE_ARCH=YES | xcpretty; test ${PIPESTATUS[0]} -eq 0
      after_success:
        - slather
        - sleep 5 # https://github.com/travis-ci/travis-ci/issues/4725
